### ISSUE TITLE
Google closure compiler exit 3221225781

### ISSUE THREAD

**Issue by maktarsis** [ampproject/rollup-plugin-closure-compiler#374]
## What's the issue?

Failed compilation on my windows laptop

## How do we reproduce the issue?

1. git clone --recursive https://github.com/maktarsis/re-space.git
2. npx yarn install
3. cd packages/example
4. npm run build

We'll likely need to know:
1. Your Rollup configuration.
https://github.com/maktarsis/re-space/blob/master/cli/src/configs/build.config.ts

2. Error logs from your console when invoking Rollup with this plugin present.
(node:8272) UnhandledPromiseRejectionWarning: Error: Google Closure Compiler exit 3221225781: C:\Users\User\projects\re-space\node_modules\google-closure
-compiler-windows\compiler.exe --language_out=NO_TRANSPILE --assume_function_wrapper=true --warning_level=QUIET --module_resolution=NODE --externs=C:\Users
\User\AppData\Local\Temp\bbd497ba00bfe80e732c9c0fdaff6eeb983c673d --externs=C:\Users\User\AppData\Local\Temp\8c3566123fa544be89f47cd1c76300842e98aa6f -
-js=C:\Users\User\AppData\Local\Temp\6cacadce9eff1166f9a4ca7149881f04cecf9ead --create_source_map=C:\Users\User\AppData\Local\Temp\0504c11f-3004-45c8-8
35e-b44622180c98

Stack trace:
  at C:\Users\Oksana\projects\re-space\node_modules\@ampproject\rollup-plugin-closure-compiler\dist\index.js:1572:24
    at ChildProcess.<anonymous> (C:\Users\Oksana\projects\re-space\node_modules\google-closure-compiler\lib\node\closure-compiler.js:103:9)
    at ChildProcess.emit (events.js:315:20)

3. Error logs when this plugin is removed from your Rollup configuration.
No errors. Just a message 'Compiled in ....s'

## Additional context

1. Node 13.13.0
2. Windows

Although, it works great as usual on my mac laptop.

**Comment by maktarsis** [comment]
It seems to me that this is some kind of problem with the environment. 
Can you tell me what the problem is?

**Comment by kristoferbaxter** [comment]
Apologies for delays looking into this. I’m out on paternity leave, but will try to address as soon as I can.

**Comment by maktarsis** [comment]
Thanks @kristoferbaxter 
I will be happy for help with this

**Comment by henriquehbr** [comment]
I'm having the exact same problem, i tried searching for a solution, but looks like this is the only place who has any information about this issue

**Comment by DVLP** [comment]
Just encountered the same problem. I have multiple projects and I noticed that some exit with this code. I'm not using this plugin just `google-closure-compiler` directly. It looks like old `google-closure-compiler` is not working well with Node 13. Newer versions of gcc package work well
